### ISSUE TITLE
sourceMappingURL in material-kit.css has the wrong file name

### ISSUE THREAD

**Issue by opeongo** [app-generator/eleventy-material-kit-pro#3]
The material-kit.css file has a sourceMappingURL instruction at line 22311:

```css
/*# sourceMappingURL=kit-pro.css.map */
```

This line points to the wrong map file, and as a result there are warnings that show up in the javascript console.

The line should probably look like:
```css
/*# sourceMappingURL=material-kit.css.map */
```

**Comment by app-generator** [comment]
Hello, 

Reference removed - Please update.
